server:
  port: 8888

spring:
  application:
    name: kah-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jhemder/microservicios-matricula-kahh.git
          search-paths: config-data
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
