server:
  port: 8080

spring:
  application:
    name: kah-gateway-server

  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://kah-student-service
          predicates:
            - Path=/api/students/**
        - id: course-service
          uri: lb://kah-course-service
          predicates:
            - Path=/api/courses/**
        - id: enrollment-service
          uri: lb://kah-enrollment-service
          predicates:
            - Path=/api/enrollments/**

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  jackson:
    time-zone: America/Lima
