spring:
  application:
    name: kah-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jhemder/microservicios-matricula-kahh.git
          search-paths: config-data
          clone-on-start: true
