server:
  port: 8080

spring:
  application:
    name: kah-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: student-service
          uri: lb://kah-student-service
          predicates:
            - Path=/students/**
        - id: course-service
          uri: lb://kah-course-service
          predicates:
            - Path=/courses/**
        - id: enrollment-service
          uri: lb://kah-enrollment-service
          predicates:
            - Path=/enrollments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
