server:
  port: 8080

spring:
  application:
    name: kah-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: kah-students
          uri: lb://kah-student-service
          predicates:
            - Path=/api/students/**
        - id: kah-courses
          uri: lb://kah-course-service
          predicates:
            - Path=/api/courses/**
        - id: kah-enrollments
          uri: lb://kah-enrollment-service
          predicates:
            - Path=/api/enrollments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
