server:
  port: 8761
spring:
  application:
    name: kah-registry-server

eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hotname}:${server.port}/eureka/
